# Generated by Django 5.0.14 on 2026-07-24 16:19

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_category_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("home_delivery", "Home Delivery"),
                            ("pickup", "Pickup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kumasi", "Kumasi"),
                            ("accra", "Accra"),
                            ("other_regions", "Other Regions"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("area", models.CharField(blank=True, default="", max_length=255)),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pv_earned", models.PositiveIntegerField(default=0)),
                ("payment_reference", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order",
                "verbose_name_plural": "historical orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("home_delivery", "Home Delivery"),
                            ("pickup", "Pickup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kumasi", "Kumasi"),
                            ("accra", "Accra"),
                            ("other_regions", "Other Regions"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("area", models.CharField(blank=True, default="", max_length=255)),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pv_earned", models.PositiveIntegerField(default=0)),
                ("payment_reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_pv", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("subtotal__gte", 0),
                    ("delivery_fee__gte", 0),
                    ("total__gte", 0),
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "+", models.F("delivery_fee")
                        ),
                    ),
                ),
                name="order_amounts_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("address", ""),
                        ("area", ""),
                        ("delivery_method", "pickup"),
                        ("delivery_zone", ""),
                    ),
                    models.Q(
                        ("delivery_method", "home_delivery"),
                        models.Q(("delivery_zone", ""), _negated=True),
                        models.Q(("address", ""), _negated=True),
                        models.Q(("area", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="order_delivery_address_required_iff_home_delivery",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1), ("unit_price__gte", 0)),
                name="order_item_quantity_and_price_sane",
            ),
        ),
    ]
