# Generated by Django 5.0.14 on 2026-07-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_historicalorder_tracking_note_order_tracking_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(unique=True)),
                ("evaluated", models.PositiveIntegerField()),
                ("cancelled", models.PositiveIntegerField()),
                ("failed", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderCycleFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.PositiveIntegerField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="orders.ordercyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id"],
            },
        ),
    ]
