# Generated by Django 5.0.14 on 2026-08-13 16:34

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_seed_auto_cancel_periodic_task"),
        ("promotions", "0002_discountcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="order_amounts_sane",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="promotions.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="promotions.discountcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("subtotal__gte", 0),
                    ("delivery_fee__gte", 0),
                    ("total__gte", 0),
                    ("discount_amount__gte", 0),
                    ("discount_amount__lte", models.F("subtotal")),
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal"), "+", models.F("delivery_fee")
                            ),
                            "-",
                            models.F("discount_amount"),
                        ),
                    ),
                ),
                name="order_amounts_sane",
            ),
        ),
    ]
