# Generated by Django 5.0.14 on 2026-08-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_review_review_pub_lookup_idx"),
        ("orders", "0005_remove_order_order_amounts_sane_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="backorders_allowed_at_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="backorders_allowed_at_checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="stock_decremented",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("stock_decremented__lte", models.F("quantity"))),
                name="order_item_stock_decremented_not_over_quantity",
            ),
        ),
    ]
