# Generated by Django 5.0.14 on 2026-08-13 21:09

from django.db import migrations, models


def backfill_stock_decremented(apps, schema_editor):
    """Task 44b. OrderItem.stock_decremented (added in the previous
    migration) defaults to 0, which is only correct for an Order that was
    never confirmed (`pending`, or cancelled before confirmation --
    nothing was ever decremented for those). Every Order that WAS
    confirmed at some point (`confirmed_at IS NOT NULL` -- set once by
    confirm_order_payment and never cleared by cancel_or_refund_order,
    even on a later cancellation/refund) had every one of its OrderItems
    decremented by exactly `quantity` under the pre-Task-44b code, which
    had no concept of a partial/backorder decrement. Without this
    backfill, a real production order confirmed before this migration
    that later gets cancelled/refunded through cancel_or_refund_order
    would silently skip restocking entirely (stock_decremented=0 reads as
    "nothing to restock"), a real regression for already-live order data,
    not just a cosmetic default."""
    OrderItem = apps.get_model("orders", "OrderItem")
    OrderItem.objects.filter(order__confirmed_at__isnull=False).update(
        stock_decremented=models.F("quantity")
    )


def noop_reverse(apps, schema_editor):
    # Not reversible in a way that distinguishes "genuinely 0" from
    # "backfilled then reversed" -- matches this codebase's own existing
    # precedent for irreversible-by-design data migrations (e.g. Task
    # 11's IrIdSequence seed). Reversing the schema migration itself
    # (0006) still works; this step is a no-op going backward.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_historicalorder_backorders_allowed_at_checkout_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_stock_decremented, noop_reverse),
    ]
