# Generated by Django 5.0.14 on 2026-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_backfill_stock_decremented_for_confirmed_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
