# Generated by Django 5.2.17 on 2026-09-17 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_historicalorder_created_at_and_more"),
        ("promotions", "0002_discountcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="receipt_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="receipt_email_sweeps",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_email_sweeps",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["receipt_email_sent_at", "confirmed_at"],
                name="order_receipt_sweep_idx",
            ),
        ),
    ]
