# Generated by Django 5.2.17 on 2026-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_seed_receipt_sweep_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="payment_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
