# Generated by Django 5.0.14 on 2026-07-22 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("distributors", "0014_distributor_mobile_money_network_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved_debited", "Approved (debited)"),
                            ("queued_for_payout", "Queued for payout"),
                            ("paid", "Paid"),
                            ("payout_failed_reversed", "Payout failed (reversed)"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payout_mobile_money_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128, region=None
                    ),
                ),
                (
                    "payout_mobile_money_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn", "MTN MoMo"),
                            ("telecel", "Telecel Cash"),
                            ("airteltigo", "AirtelTigo Money"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "paystack_recipient_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "paystack_transfer_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="distributors.distributor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical withdrawal request",
                "verbose_name_plural": "historical withdrawal requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved_debited", "Approved (debited)"),
                            ("queued_for_payout", "Queued for payout"),
                            ("paid", "Paid"),
                            ("payout_failed_reversed", "Payout failed (reversed)"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payout_mobile_money_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128, region=None
                    ),
                ),
                (
                    "payout_mobile_money_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mtn", "MTN MoMo"),
                            ("telecel", "Telecel Cash"),
                            ("airteltigo", "AirtelTigo Money"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "paystack_recipient_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "paystack_transfer_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="distributors.distributor",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("net_amount__gte", 0),
                    ("net_amount__lte", models.F("amount")),
                ),
                name="withdrawal_request_amounts_sane",
            ),
        ),
    ]
