# Generated by Django 5.0.14 on 2026-07-22 23:24

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0014_distributor_mobile_money_network_and_more"),
        ("withdrawal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="withdrawalrequest",
            name="withdrawal_request_amounts_sane",
        ),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("amount__gte", 0),
                    ("tax_amount__gte", 0),
                    ("net_amount__gte", 0),
                    (
                        "amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("tax_amount"), "+", models.F("net_amount")
                        ),
                    ),
                ),
                name="withdrawal_request_amounts_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("payout_mobile_money_network", ""),
                        ("payout_mobile_money_number", ""),
                    ),
                    models.Q(
                        models.Q(("payout_mobile_money_number", ""), _negated=True),
                        models.Q(("payout_mobile_money_network", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="withdrawal_request_payout_snapshot_both_or_neither",
            ),
        ),
    ]
