# Generated by Django 5.0.14 on 2026-07-22 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0014_distributor_mobile_money_network_and_more"),
        (
            "withdrawal",
            "0002_remove_withdrawalrequest_withdrawal_request_amounts_sane_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["distributor", "status", "created_at"],
                name="withdrawal__distrib_a10f81_idx",
            ),
        ),
    ]
