# Generated by Django 5.0.14 on 2026-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal", "0003_withdrawalrequest_withdrawal__distrib_a10f81_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwithdrawalrequest",
            name="payout_recipient_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payout_recipient_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
