# Generated by Django 5.0.14 on 2026-07-24 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0014_distributor_mobile_money_network_and_more"),
        (
            "withdrawal",
            "0004_historicalwithdrawalrequest_payout_recipient_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalCycleFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("withdrawal_request_id", models.PositiveIntegerField()),
                ("distributor_id", models.PositiveIntegerField(null=True)),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["withdrawal_request_id"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(unique=True)),
                ("evaluated", models.PositiveIntegerField()),
                ("paid", models.PositiveIntegerField()),
                ("failed", models.PositiveIntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["status", "created_at"], name="withdrawal__status_8516f2_idx"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalcyclefailure",
            name="cycle_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failures",
                to="withdrawal.withdrawalcyclerun",
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawalcyclefailure",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("distributor_id__isnull", True), ("net_amount__isnull", True)
                    ),
                    models.Q(
                        ("distributor_id__isnull", False), ("net_amount__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="withdrawal_cycle_failure_snapshot_both_or_neither",
            ),
        ),
    ]
