# Generated by Django 5.2.17 on 2026-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal", "0006_seed_withdrawal_payout_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwithdrawalrequest",
            name="queued_for_payout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="queued_for_payout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
