# Generated by Django 5.0.14 on 2026-08-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0008_review_review_pub_lookup_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOrderRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("orders_pending", models.PositiveIntegerField(default=0)),
                ("orders_confirmed", models.PositiveIntegerField(default=0)),
                ("orders_processing", models.PositiveIntegerField(default=0)),
                ("orders_dispatched", models.PositiveIntegerField(default=0)),
                ("orders_delivered", models.PositiveIntegerField(default=0)),
                ("orders_cancelled", models.PositiveIntegerField(default=0)),
                ("orders_refunded", models.PositiveIntegerField(default=0)),
                (
                    "delivery_fees_kumasi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "delivery_fees_accra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "delivery_fees_other_regions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ReportRollupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollup_date", models.DateField()),
                ("run_at", models.DateTimeField()),
                ("succeeded", models.BooleanField()),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyProductSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("product_name", models.CharField(max_length=255)),
                ("units_sold", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-units_sold"],
            },
        ),
        migrations.AddConstraint(
            model_name="reportrolluprun",
            constraint=models.UniqueConstraint(
                fields=("rollup_date", "run_at"), name="unique_rollup_date_run_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyproductsales",
            constraint=models.UniqueConstraint(
                fields=("date", "product"),
                name="unique_daily_product_sales_date_product",
            ),
        ),
    ]
