# Generated by Django 5.0.14 on 2026-07-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("distributors", "0002_distributor_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryTreeEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                (
                    "leg",
                    models.CharField(
                        choices=[("L", "Left"), ("R", "Right")], max_length=1
                    ),
                ),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendant_edges",
                        to="distributors.distributor",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestor_edges",
                        to="distributors.distributor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ancestor", "leg"],
                        name="binary_tree_ancesto_f29b27_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="binarytreeedge",
            constraint=models.UniqueConstraint(
                fields=("ancestor", "descendant"), name="unique_binary_tree_edge"
            ),
        ),
        migrations.AddConstraint(
            model_name="binarytreeedge",
            constraint=models.CheckConstraint(
                check=models.Q(("ancestor", models.F("descendant")), _negated=True),
                name="binary_tree_edge_no_self_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="binarytreeedge",
            constraint=models.CheckConstraint(
                check=models.Q(("depth__gte", 1)), name="binary_tree_edge_depth_gte_1"
            ),
        ),
    ]
