# Generated by Django 5.0.14 on 2026-07-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissions", "0001_seed_binary_bonus_periodic_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryBonusCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(unique=True)),
                ("evaluated", models.PositiveIntegerField()),
                ("paid", models.PositiveIntegerField()),
                ("failed", models.PositiveIntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="BinaryBonusCycleFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distributor_id", models.PositiveIntegerField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="commissions.binarybonuscyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["distributor_id"],
            },
        ),
    ]
