# Generated by Django 5.0.14 on 2026-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Customers Only"),
                            ("distributor", "Distributors Only"),
                            ("everyone", "Everyone"),
                        ],
                        default="everyone",
                        max_length=15,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        help_text="Global cap across all customers."
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("limit_one_per_customer", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
