# Generated by Django 5.0.14 on 2026-08-14 21:11

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscrowLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EscrowTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("reversal", "Reversal")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("rate_applied", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="escrowledger",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="escrow_ledger_balance_gte_0"
            ),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="ledger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="compliance.escrowledger",
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["order_id"], name="compliance__order_i_936a65_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowtransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("amount__gt", 0), ("transaction_type", "credit")),
                    models.Q(("amount__lt", 0), ("transaction_type", "reversal")),
                    _connector="OR",
                ),
                name="escrow_transaction_sign_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowtransaction",
            constraint=models.UniqueConstraint(
                fields=("order_id", "transaction_type"),
                name="unique_escrow_transaction_order_type",
            ),
        ),
    ]
