# Generated by Django 5.0.14 on 2026-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_seed_escrow_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceAlertState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_below_threshold", models.BooleanField(default=False)),
                ("last_alert_sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
