# Generated by Django 5.0.14 on 2026-07-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("wallet", "reference", "transaction_type"),
                name="unique_wallet_reference_transaction_type",
            ),
        ),
    ]
