# Generated by Django 5.0.14 on 2026-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wallettransaction",
            name="unique_wallet_reference_transaction_type",
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                fields=("wallet", "reference", "transaction_type"),
                name="unique_wallet_reference_transaction_type",
            ),
        ),
    ]
