# Generated by Django 5.0.14 on 2026-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0004_remove_wallettransaction_unique_wallet_reference_transaction_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("direct_referral_bonus", "Direct Referral Bonus"),
                    ("binary_bonus", "Binary Bonus"),
                    ("matching_bonus", "Matching Bonus"),
                ],
                max_length=30,
            ),
        ),
    ]
