# Generated by Django 5.0.14 on 2026-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0013_alter_distributor_rank_and_more"),
        ("wallet", "0005_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("direct_referral_bonus", "Direct Referral Bonus"),
                    ("binary_bonus", "Binary Bonus"),
                    ("matching_bonus", "Matching Bonus"),
                    ("withdrawal_debit", "Withdrawal Debit"),
                    ("refund_reversal", "Refund Reversal"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="wallet_balance_gte_0"
            ),
        ),
    ]
