# Generated by Django 5.0.14 on 2026-07-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_alter_wallettransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("direct_referral_bonus", "Direct Referral Bonus"),
                    ("binary_bonus", "Binary Bonus"),
                    ("matching_bonus", "Matching Bonus"),
                    ("withdrawal_debit", "Withdrawal Debit"),
                    ("refund_reversal", "Refund Reversal"),
                    ("withdrawal_reversal", "Withdrawal Reversal"),
                ],
                max_length=30,
            ),
        ),
    ]
