# Generated by Django 5.0.14 on 2026-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="wallettxn_type_created_idx",
            ),
        ),
    ]
