# Generated by Django 5.0.14 on 2026-08-11 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=500)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("pinterest", "Pinterest"),
                            ("snapchat", "Snapchat"),
                            ("reddit", "Reddit"),
                            ("discord", "Discord"),
                            ("threads", "Threads"),
                            ("github", "GitHub"),
                            ("twitch", "Twitch"),
                            ("spotify", "Spotify"),
                            ("medium", "Medium"),
                            ("wechat", "WeChat"),
                            ("custom", "Other / Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 6-digit hex color, e.g. #1877F2.",
                                regex="\\A#[0-9A-Fa-f]{6}\\Z",
                            )
                        ],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
    ]
