# Generated by Django 5.0.14 on 2026-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("x", "X (Twitter)"),
                    ("youtube", "YouTube"),
                    ("tiktok", "TikTok"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("pinterest", "Pinterest"),
                    ("snapchat", "Snapchat"),
                    ("reddit", "Reddit"),
                    ("discord", "Discord"),
                    ("threads", "Threads"),
                    ("github", "GitHub"),
                    ("twitch", "Twitch"),
                    ("spotify", "Spotify"),
                    ("medium", "Medium"),
                    ("wechat", "WeChat"),
                    ("custom", "Other / Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
