# Generated by Django 5.0.14 on 2026-07-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("distributors", "0002_distributor_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PvLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_leg_pv", models.PositiveIntegerField(default=0)),
                ("right_leg_pv", models.PositiveIntegerField(default=0)),
                (
                    "distributor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pv_ledger",
                        to="distributors.distributor",
                    ),
                ),
            ],
        ),
    ]
