# Generated by Django 5.0.14 on 2026-07-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0012_historicaldistributor"),
        ("pv_ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyPersonalPv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("pv", models.PositiveIntegerField(default=0)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_personal_pv",
                        to="distributors.distributor",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monthlypersonalpv",
            constraint=models.UniqueConstraint(
                fields=("distributor", "period"),
                name="unique_distributor_period_personal_pv",
            ),
        ),
    ]
