# Generated by Django 5.0.14 on 2026-07-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0012_historicaldistributor"),
        ("pv_ledger", "0002_monthlypersonalpv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PvDailyBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leg",
                    models.CharField(
                        choices=[("L", "Left"), ("R", "Right")], max_length=1
                    ),
                ),
                ("date", models.DateField()),
                ("pv", models.PositiveIntegerField(default=0)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pv_daily_buckets",
                        to="distributors.distributor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["distributor", "date"],
                        name="pv_ledger_p_distrib_ecac0a_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pvdailybucket",
            constraint=models.UniqueConstraint(
                fields=("distributor", "leg", "date"),
                name="unique_distributor_leg_date_pv_bucket",
            ),
        ),
    ]
