# Generated by Django 5.0.14 on 2026-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0012_historicaldistributor"),
        ("pv_ledger", "0003_pvdailybucket_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pvdailybucket",
            constraint=models.CheckConstraint(
                check=models.Q(("pv__gte", 0)), name="pv_daily_bucket_pv_gte_0"
            ),
        ),
    ]
