# Generated by Django 5.0.14 on 2026-07-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Shown on the storefront's category tile (Task 8). Optional — categories without one render as a plain text tile.",
                upload_to="categories/",
            ),
        ),
    ]
