# Generated by Django 5.0.14 on 2026-08-12 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_review_review_unique_review_per_user_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "is_approved", "-created_at"],
                name="review_pub_lookup_idx",
            ),
        ),
    ]
