# Generated by Django 5.0.14 on 2026-07-11 10:09

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distributor",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distributor",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region=None, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distributor",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
    ]
