# Generated by Django 5.0.14 on 2026-07-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0004_seed_cleanup_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="distributor",
            name="area",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="distributor",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="distributor",
            name="landmark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="fee_amount_pesewas",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
