# Generated by Django 5.0.14 on 2026-07-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0005_distributor_address_distributor_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="starter_pack_choice",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="distributor",
            name="starter_pack_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distributor",
            name="starter_pack_payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="distributor",
            name="starter_pack_price_pesewas",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distributor",
            name="starter_pack_pv",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distributor",
            name="starter_pack_rank",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
