# Generated by Django 5.0.14 on 2026-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0006_distributor_starter_pack_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="ghana_card_back",
            field=models.ImageField(blank=True, upload_to="kyc/ghana_card_back/"),
        ),
        migrations.AddField(
            model_name="distributor",
            name="ghana_card_front",
            field=models.ImageField(blank=True, upload_to="kyc/ghana_card_front/"),
        ),
        migrations.AddField(
            model_name="distributor",
            name="kyc_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distributor",
            name="selfie",
            field=models.ImageField(blank=True, upload_to="kyc/selfie/"),
        ),
    ]
