# Generated by Django 5.0.14 on 2026-07-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0007_distributor_ghana_card_back_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributor",
            name="ghana_card_back",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="ghana_card_front",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="kyc_submitted_at",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="selfie",
        ),
    ]
