# Generated by Django 5.0.14 on 2026-07-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0008_remove_distributor_ghana_card_back_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiditVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("in_review", "In Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "id_verification_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "face_match_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("face_match_score", models.FloatField(blank=True, null=True)),
                (
                    "liveness_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("liveness_score", models.FloatField(blank=True, null=True)),
                (
                    "extracted_full_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "extracted_document_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("extracted_date_of_birth", models.DateField(blank=True, null=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "id_front_image",
                    models.ImageField(blank=True, upload_to="kyc/didit/id_front/"),
                ),
                (
                    "id_back_image",
                    models.ImageField(blank=True, upload_to="kyc/didit/id_back/"),
                ),
                (
                    "selfie_image",
                    models.ImageField(blank=True, upload_to="kyc/didit/selfie/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distributor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="didit_verification",
                        to="distributors.distributor",
                    ),
                ),
            ],
        ),
    ]
