# Generated by Django 5.0.14 on 2026-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0009_diditverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrIdSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_number", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="distributor",
            name="kyc_rejection_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
