# Generated by Django 5.0.14 on 2026-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0012_historicaldistributor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributor",
            name="rank",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicaldistributor",
            name="rank",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
    ]
