# Generated by Django 5.0.14 on 2026-07-22 21:37

import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0013_alter_distributor_rank_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="mobile_money_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN MoMo"),
                    ("telecel", "Telecel Cash"),
                    ("airteltigo", "AirtelTigo Money"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="mobile_money_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="historicaldistributor",
            name="mobile_money_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN MoMo"),
                    ("telecel", "Telecel Cash"),
                    ("airteltigo", "AirtelTigo Money"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaldistributor",
            name="mobile_money_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, region=None
            ),
        ),
        migrations.AddConstraint(
            model_name="distributor",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("mobile_money_network", ""), ("mobile_money_number", "")),
                    models.Q(
                        models.Q(("mobile_money_number", ""), _negated=True),
                        models.Q(("mobile_money_network", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="distributor_payout_destination_both_or_neither",
            ),
        ),
    ]
