# Generated by Django 5.0.14 on 2026-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0014_distributor_mobile_money_network_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="cooling_off_cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldistributor",
            name="cooling_off_cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
