# Generated by Django 5.2.17 on 2026-08-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0015_distributor_cooling_off_cancelled_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RootDistributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distributor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="distributors.distributor",
                    ),
                ),
            ],
        ),
    ]
