# Generated by Django 5.2.17 on 2026-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0017_seed_root_distributor_singleton"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "registration_unmatched",
                                "Registration fee paid, no registration found",
                            ),
                            ("registration_duplicate", "Registration fee paid twice"),
                            (
                                "registration_not_created",
                                "Registration fee paid, account could not be created",
                            ),
                            (
                                "registration_unconfirmed",
                                "Registration payment could not be confirmed with Paystack",
                            ),
                            (
                                "starter_pack_not_applied",
                                "Starter pack paid, not applied",
                            ),
                            ("order_not_applied", "Order paid, not confirmed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("amount_pesewas", models.PositiveIntegerField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "payer_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "payer_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="consumed_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="payment_initialized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
