# Generated by Django 5.2.17 on 2026-09-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0020_seed_payment_reconciliation_periodic_task"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pendingregistration",
            index=models.Index(
                fields=["consumed_at", "last_checked_at"], name="pendingreg_cleanup_idx"
            ),
        ),
    ]
