# Generated by Django 5.2.17 on 2026-09-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0023_withdrawal_not_paid_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentissue",
            name="kind",
            field=models.CharField(
                choices=[
                    (
                        "registration_unmatched",
                        "Registration fee paid, no registration found",
                    ),
                    ("registration_duplicate", "Registration fee paid twice"),
                    (
                        "registration_not_created",
                        "Registration fee paid, account could not be created",
                    ),
                    (
                        "registration_unconfirmed",
                        "Registration payment could not be confirmed with Paystack",
                    ),
                    ("starter_pack_not_applied", "Starter pack paid, not applied"),
                    ("order_not_applied", "Order paid, not confirmed"),
                    ("refund_received", "Payment refunded on Paystack"),
                    ("dispute_opened", "Customer disputed a payment"),
                    (
                        "withdrawal_not_paid",
                        "Withdrawal debited, payout never confirmed",
                    ),
                    ("unrecognised_payment", "Payment not from a Bancostore checkout"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="StarterPackCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("amount_pesewas", models.PositiveIntegerField()),
                ("choice", models.CharField(max_length=1)),
                ("pv", models.PositiveIntegerField(default=0)),
                ("rank", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starter_pack_checkouts",
                        to="distributors.distributor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
