# Generated by Django 5.2.17 on 2026-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0025_backfill_starter_pack_checkouts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentissue",
            name="kind",
            field=models.CharField(
                choices=[
                    (
                        "registration_unmatched",
                        "Registration fee paid, no registration found",
                    ),
                    ("registration_duplicate", "Registration fee paid twice"),
                    (
                        "registration_not_created",
                        "Registration fee paid, account could not be created",
                    ),
                    (
                        "registration_unconfirmed",
                        "Registration payment could not be confirmed with Paystack",
                    ),
                    ("starter_pack_not_applied", "Starter pack paid, not applied"),
                    ("order_not_applied", "Order paid, not confirmed"),
                    ("refund_received", "Payment refunded on Paystack"),
                    ("dispute_opened", "Customer disputed a payment"),
                    (
                        "withdrawal_not_paid",
                        "Withdrawal debited, payout never confirmed",
                    ),
                    ("unrecognised_payment", "Payment not from a Bancostore checkout"),
                ],
                max_length=40,
            ),
        ),
    ]
