# Generated by Django 5.2.17 on 2026-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0026_refund_and_dispute_kinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpackcheckout",
            name="refund_handled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
