# Generated by Django 5.0.14 on 2026-07-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributors", "0015_distributor_cooling_off_cancelled_at_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("downline_joined", "New downline member"),
                            ("binary_bonus_credited", "Binary bonus credited"),
                            ("referral_bonus_paid", "Referral bonus paid"),
                            ("withdrawal_approved", "Withdrawal approved"),
                            ("kyc_decided", "KYC decision"),
                            ("pv_expiring", "PV approaching expiry"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="distributors.distributor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["distributor", "-created_at"],
                        name="notificatio_distrib_751a67_idx",
                    ),
                    models.Index(
                        fields=["distributor", "is_read"],
                        name="notificatio_distrib_ffbf74_idx",
                    ),
                ],
            },
        ),
    ]
