# Generated by Django 5.0.14 on 2026-07-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(unique=True)),
                ("evaluated", models.PositiveIntegerField()),
                ("notified", models.PositiveIntegerField()),
                ("failed", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationCycleFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distributor_id", models.PositiveIntegerField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="notifications.notificationcyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["distributor_id"],
            },
        ),
    ]
