# Generated by Django 5.0.14 on 2026-08-15 20:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_seed_pv_expiry_periodic_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("otp_code", "OTP Verification Code (SMS)"),
                            ("withdrawal_approved", "Withdrawal Approved (SMS)"),
                            ("withdrawal_rejected", "Withdrawal Rejected (SMS)"),
                            ("withdrawal_paid", "Withdrawal Paid (SMS)"),
                            ("withdrawal_reversed", "Withdrawal Reversed (SMS)"),
                            ("kyc_approved", "KYC Approved (In-App Notification)"),
                            ("kyc_rejected", "KYC Rejected (In-App Notification)"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("otp_code", "OTP Verification Code (SMS)"),
                            ("withdrawal_approved", "Withdrawal Approved (SMS)"),
                            ("withdrawal_rejected", "Withdrawal Rejected (SMS)"),
                            ("withdrawal_paid", "Withdrawal Paid (SMS)"),
                            ("withdrawal_reversed", "Withdrawal Reversed (SMS)"),
                            ("kyc_approved", "KYC Approved (In-App Notification)"),
                            ("kyc_rejected", "KYC Rejected (In-App Notification)"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField()),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical notification template",
                "verbose_name_plural": "historical notification templates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
