# Generated by Django 5.0.14 on 2026-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_seed_more_notification_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnotificationtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("otp_code", "OTP Verification Code (SMS)"),
                    ("withdrawal_approved", "Withdrawal Approved (SMS)"),
                    ("withdrawal_rejected", "Withdrawal Rejected (SMS)"),
                    ("withdrawal_paid", "Withdrawal Paid (SMS)"),
                    ("withdrawal_reversed", "Withdrawal Reversed (SMS)"),
                    ("kyc_approved", "KYC Approved (In-App Notification)"),
                    ("kyc_rejected", "KYC Rejected (In-App Notification)"),
                    (
                        "binary_bonus_credited",
                        "Binary Bonus Credited (In-App Notification)",
                    ),
                    ("downline_joined", "New Downline Member (In-App Notification)"),
                    (
                        "direct_referral_bonus_credited_sms",
                        "Direct Referral Bonus Credited (SMS)",
                    ),
                    (
                        "direct_referral_bonus_credited_inapp",
                        "Direct Referral Bonus Credited (In-App Notification)",
                    ),
                    ("pv_expiring", "PV Approaching Expiry (In-App Notification)"),
                    ("order_status_update_sms", "Order Status Update (SMS)"),
                    ("order_status_update_email", "Order Status Update (Email)"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("otp_code", "OTP Verification Code (SMS)"),
                    ("withdrawal_approved", "Withdrawal Approved (SMS)"),
                    ("withdrawal_rejected", "Withdrawal Rejected (SMS)"),
                    ("withdrawal_paid", "Withdrawal Paid (SMS)"),
                    ("withdrawal_reversed", "Withdrawal Reversed (SMS)"),
                    ("kyc_approved", "KYC Approved (In-App Notification)"),
                    ("kyc_rejected", "KYC Rejected (In-App Notification)"),
                    (
                        "binary_bonus_credited",
                        "Binary Bonus Credited (In-App Notification)",
                    ),
                    ("downline_joined", "New Downline Member (In-App Notification)"),
                    (
                        "direct_referral_bonus_credited_sms",
                        "Direct Referral Bonus Credited (SMS)",
                    ),
                    (
                        "direct_referral_bonus_credited_inapp",
                        "Direct Referral Bonus Credited (In-App Notification)",
                    ),
                    ("pv_expiring", "PV Approaching Expiry (In-App Notification)"),
                    ("order_status_update_sms", "Order Status Update (SMS)"),
                    ("order_status_update_email", "Order Status Update (Email)"),
                ],
                max_length=40,
                unique=True,
            ),
        ),
    ]
