# Generated by Django 5.2.17 on 2026-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_add_admin_notification"),
        ("orders", "0008_alter_historicalorder_created_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["-created_at", "-id"], name="notificatio_created_405dec_idx"
            ),
        ),
    ]
