# Generated by Django 5.2.17 on 2026-09-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_seed_order_receipt_text_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_order", "New order paid"),
                    ("sms_credit", "SMS credit low"),
                ],
                max_length=32,
            ),
        ),
    ]
