# Generated by Django 5.2.17 on 2026-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0018_seed_sms_credit_check_periodic_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsCreditStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits", models.IntegerField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("shortage_started_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "SMS credit status",
            },
        ),
    ]
