# Generated by Django 5.2.17 on 2026-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0019_add_sms_credit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_order", "New order paid"),
                    ("sms_credit", "SMS credit low"),
                    ("payment_issue", "Payment needs attention"),
                ],
                max_length=32,
            ),
        ),
    ]
